
spring:
  application:
    name: runnershopservice
  cloud:
    nacos:
      discovery: #使用nacos作为服务的注册中心
        server-addr: 39.99.158.56:8848
      config: #使用nacos作为服务的配置中心
        server-addr: 39.99.158.56:8848
        #file-extension: yaml #更改远程配置的后缀名
  #  sleuth:
  #    sampler:
  #      probability: 1 #采样率
  #    zipkin:
  #      sender:
  #        type: web #使用http协议进行数据的传输
  #      base-url: 39.99.158.56:9411/ #zipkin的控制台的地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_runner?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
server:
  port: 8088



